# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-22 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agridata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=50)),
                ('crop_year', models.IntegerField(default=2002)),
                ('season', models.CharField(max_length=50)),
                ('crop', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('production', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rainfall', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
