# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-22 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agridata',
            name='rainfall',
            field=models.IntegerField(default=0),
        ),
    ]
