# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMain', '0002_auto_20180322_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
