# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMain', '0003_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(blank=True, null=True, upload_to='data/')),
                ('accuracy', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('hfile', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
