# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-07 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgroMain', '0004_analysisfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisfiles',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='analysisfiles',
            name='hfile',
        ),
    ]
